version "3"

services:
  rabbitmq:
    image: rabbitmq:3-management 
    ports:
      - "15672:15672"
      - "5672:5672"
  
  rabbitmq-reader-loop:
    build: .
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__host: rabbitmq